// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import path from 'node:path';
import { defineConfig } from 'prisma/config';

const databaseUrl =
    process.env.DIRECT_URL || process.env.DATABASE_URL || 'postgresql://postgres:postgres@localhost:5444/postgres';

export default defineConfig({
    schema: path.join(__dirname, 'prisma', 'schema.prisma'),
    migrations: {
        path: path.join(__dirname, 'prisma', 'schema.prisma'),
    },
    datasource: {
        url: databaseUrl,
    },
});
